### ISSUE TITLE
Can’t work in 1.19

### ISSUE THREAD

**Issue by mokong101** [SofiaRedmond/Slimefun-Geyser#1] opened 2022-06-10 12:34 UTC
The Minecraft bedrock edition is update to 1.19.But the resource can’t work in bedrock 1.19.Please fix it.

**Comment by SofiaRedmond** [comment] 2022-06-12 23:25
The GeyserMC plugin (with custom mapping) has not been merged with the GeyserMC 1.19 update (as far as I know), until this happens, this resource cannot work as intended.

**Closed as completed** 2022-06-19 03:00 UTC
